"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will 
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
"""

UPPER_LIMIT = 4 * 10 ** 6


a = 1
b = 2
even_fibonacci_sum = 0


def _is_even(number):
    return number % 2 == 0


def add_to_sum_if_even(input_sum, term):
    if _is_even(term):
        output_sum = input_sum + term
    else:
        output_sum = input_sum
    return output_sum


while b <= UPPER_LIMIT:
    even_fibonacci_sum = add_to_sum_if_even(even_fibonacci_sum, b)
    a, b = b, a + b

print(even_fibonacci_sum)
