'''
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will 
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
'''

a = 1
b = 2

upper_limit = 4*10**6
sum = 0


while b <= upper_limit:
	# Print first part of Fibonacci sequence for sanity check:
	if a < 100:
		print(a)
	
	# Add to sum if even:
	if b%2==0:
		sum = sum+b
	
	# Generate next pair in Fibonacci seequence:
	a,b = b,a+b


print(sum)

